server:
  port: 18081

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_ZONE_HOST:localhost}:${EUREKA_ZONE_PORT:8761}/eureka/

spring:
  application:
    name: xxl-job-executor
#  jackson:
#    time-zone: GMT+8
#    date-format: yyyy-MM-dd HH:mm:ss

  rabbitmq:
    host: ${RABBIT_MQ_HOST:190.168.0.77}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:admin}
    password: ${RABBIT_MQ_PASSWORD:admin}
  redis:
    host: ${REDIS_HOST:190.168.0.78}
    port: ${REDIS_PORT:6379}
    lettuce:
      pool:
        max-active: 300
    #password: ${REDIS_PASSWORD:123456}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:190.168.0.77}:${MYSQL_PORT:3306}/spring_cloud?useUnicode=true&useSSL=false
    username: ${MYSQL_USERNAME:dev_user}
    password: ${MYSQL_PASSWORD:Sfc@123456}
    driver-class-name: com.mysql.cj.jdbc.Driver

  devtools:
    restart:
      log-condition-evaluation-delta: false

  zipkin:
    enabled: true
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1.0

  mvc:
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      max-request-size: "20MB"
      max-file-size: "20MB"


#  resources:
#    add-mappings: false

logging:
  level:
    org.springframework.cloud.sleuth: info
    java.sql.PreparedStatement: info
    com.sfc.demos.producer.dao: info
  path: logs/
  file:
    max-size: 1GB

management:
  endpoints:
    web:
      exposure:
        include: '*'

mybatis:
  configuration:
    map-underscore-to-camel-case: true


### xxl-job admin address list：调度中心部署跟地址：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"。
xxl:
  job:
    executor:
      logpath: /data/applogs/xxl-job/jobhandler
      appname: xxl-job-executor
      port: 9999
      logretentiondays: -1
      ip:
    admin:
      addresses: http://190.168.0.78:18080/xxl-job-admin
    accessToken: